version: '3'
services:
  backend:
    build:
      context: ./Backend
    environment:
      - MONGO_URI=mongodb+srv://adityarajsahoouser:adityarajsahoo@cluster0.ajk0wyt.mongodb.net/?retryWrites=true&w=majority
    ports:
      - '9000:9000'
    restart: always
  frontend:
    build:
      context: ./Frontend
    ports:
      - '3000:3000'
    restart: always
