version: '3'
services:
  backend:
    image: backend:1.0
    environment:
      - MONGO_URI=mongodb+srv://adityarajsahoouser:adityarajsahoo@cluster0.ajk0wyt.mongodb.net/?retryWrites=true&w=majority
    ports:
      - '9000:9000'
    restart: always
  frontend:
    image: frontend:1.0
    ports:
      - '3000:3000'
    restart: always
